openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/projects:
    get:
      summary: 'Get projects list'
      operationId: getProjectsList
      description: 'Return projects list.'
      parameters:
        -
          in: query
          name: size
          description: 'Number of rows. Default: 50'
          example: 15
          required: false
          schema:
            type: integer
            description: 'Number of rows. Default: 50'
            example: 15
        -
          in: query
          name: page
          description: 'Number of page (pagination). Default: 1'
          example: 14
          required: false
          schema:
            type: integer
            description: 'Number of page (pagination). Default: 1'
            example: 14
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  total_rows: 100
                  total_pages: '4'
                  current_page: 1
                  has_more: true
                  data:
                    -
                      id: 1
                      name: 'Test project'
                      location: Warsaw
                      description: ''
                      owner: john@doe.com
                properties:
                  total_rows:
                    type: integer
                    example: 100
                  total_pages:
                    type: string
                    example: '4'
                  current_page:
                    type: integer
                    example: 1
                  has_more:
                    type: boolean
                    example: true
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'Test project'
                        location: Warsaw
                        description: ''
                        owner: john@doe.com
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Test project'
                        location:
                          type: string
                          example: Warsaw
                        description:
                          type: string
                          example: ''
                        owner:
                          type: string
                          example: john@doe.com
      tags:
        - Projects
      security: []
  /api/project:
    put:
      summary: 'Create new project'
      operationId: createNewProject
      description: 'Create new project.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses: {  }
      tags:
        - Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Project name.'
                  example: illo
                location:
                  type: string
                  description: 'Project location.'
                  example: non
                description:
                  type: string
                  description: 'Project description.'
                  example: 'Doloremque est earum nostrum maiores reprehenderit voluptatem laborum aliquid.'
                owner:
                  type: string
                  description: 'Project owner.'
                  example: nostrum
              required:
                - name
      security: []
  '/api/project/{id}':
    get:
      summary: 'Get project details'
      operationId: getProjectDetails
      description: 'Return project details.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 'Test project'
                  location: Warsaw
                  description: ''
                  owner: john@doe.com
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'Test project'
                  location:
                    type: string
                    example: Warsaw
                  description:
                    type: string
                    example: ''
                  owner:
                    type: string
                    example: john@doe.com
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Project does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Project does not exist'
      tags:
        - Projects
      security: []
    put:
      summary: 'Update project'
      operationId: updateProject
      description: 'Update project.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses: {  }
      tags:
        - Projects
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Project name.'
                  example: reiciendis
                location:
                  type: string
                  description: 'Project location.'
                  example: natus
                description:
                  type: string
                  description: 'Project description.'
                  example: 'Consequuntur vitae distinctio consequatur ut commodi libero.'
                owner:
                  type: string
                  description: 'Project owner.'
                  example: odit
      security: []
    delete:
      summary: 'Delete project'
      operationId: deleteProject
      description: 'Delete project.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Project does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Project does not exist'
      tags:
        - Projects
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Project identifier.'
        example: 20
        required: true
        schema:
          type: integer
  /api/users:
    get:
      summary: 'Get users list'
      operationId: getUsersList
      description: 'Return users account list.'
      parameters:
        -
          in: query
          name: size
          description: 'Number of rows. Default: 50'
          example: 16
          required: false
          schema:
            type: integer
            description: 'Number of rows. Default: 50'
            example: 16
        -
          in: query
          name: page
          description: 'Number of page (pagination). Default: 1'
          example: 10
          required: false
          schema:
            type: integer
            description: 'Number of page (pagination). Default: 1'
            example: 10
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  total_rows: 100
                  total_pages: '4'
                  current_page: 1
                  has_more: true
                  data:
                    -
                      id: 1
                      firstname: John
                      lastname: Doe
                      phone: 123456789
                      email: john@doe.com
                      activated: 1
                      owner: 0
                      superuser: 0
                      user_permission_id: 1
                properties:
                  total_rows:
                    type: integer
                    example: 100
                  total_pages:
                    type: string
                    example: '4'
                  current_page:
                    type: integer
                    example: 1
                  has_more:
                    type: boolean
                    example: true
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        firstname: John
                        lastname: Doe
                        phone: 123456789
                        email: john@doe.com
                        activated: 1
                        owner: 0
                        superuser: 0
                        user_permission_id: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        firstname:
                          type: string
                          example: John
                        lastname:
                          type: string
                          example: Doe
                        phone:
                          type: integer
                          example: 123456789
                        email:
                          type: string
                          example: john@doe.com
                        activated:
                          type: integer
                          example: 1
                        owner:
                          type: integer
                          example: 0
                        superuser:
                          type: integer
                          example: 0
                        user_permission_id:
                          type: integer
                          example: 1
      tags:
        - 'User management'
      security: []
  /api/user:
    put:
      summary: 'Create user account'
      operationId: createUserAccount
      description: 'Create user account. After create account is ready to use.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        409:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The given e-mail address is already registered'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The given e-mail address is already registered'
      tags:
        - 'User management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'User first name.'
                  example: laboriosam
                lastname:
                  type: string
                  description: 'User last name.'
                  example: sint
                email:
                  type: string
                  description: 'User e-mail address.'
                  example: bulah78@example.net
                password:
                  type: string
                  description: 'User password (min 8 characters, lowercase and uppercase letters, number, special characters).'
                  example: 2S()sKN
                phone:
                  type: string
                  description: 'User phone number.'
                  example: voluptas
                permission_id:
                  type: integer
                  description: 'Permission group identifier (if not set default permission will be used).'
                  example: 7
                superuser:
                  type: boolean
                  description: 'If set true user have full access regardless of permissions.'
                  example: true
              required:
                - firstname
                - lastname
                - email
                - password
      security: []
  /api/invite:
    post:
      summary: 'Invite user'
      operationId: inviteUser
      description: 'Send invitation to the email address provided.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        409:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The given e-mail address is already registered'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The given e-mail address is already registered'
      tags:
        - 'User management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'User e-mail address.'
                  example: danny.ortiz@example.net
                permission_id:
                  type: integer
                  description: 'Permission group identifier (if not set default permission will be used).'
                  example: 16
              required:
                - email
      security: []
  '/api/user/{id}':
    get:
      summary: 'Get user account data'
      operationId: getUserAccountData
      description: 'Return user account data.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  firstname: John
                  lastname: Doe
                  phone: 123456789
                  email: john@doe.com
                  activated: 1
                  owner: 0
                  superuser: 0
                  user_permission_id: 1
                properties:
                  id:
                    type: integer
                    example: 1
                  firstname:
                    type: string
                    example: John
                  lastname:
                    type: string
                    example: Doe
                  phone:
                    type: integer
                    example: 123456789
                  email:
                    type: string
                    example: john@doe.com
                  activated:
                    type: integer
                    example: 1
                  owner:
                    type: integer
                    example: 0
                  superuser:
                    type: integer
                    example: 0
                  user_permission_id:
                    type: integer
                    example: 1
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'User does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User does not exist'
      tags:
        - 'User management'
      security: []
    put:
      summary: 'Update user account data'
      operationId: updateUserAccountData
      description: 'Update user account data.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses: {  }
      tags:
        - 'User management'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'User first name.'
                  example: incidunt
                lastname:
                  type: string
                  description: 'User last name.'
                  example: ut
                email:
                  type: string
                  description: 'User e-mail address.'
                  example: ottis33@example.org
                password:
                  type: string
                  description: 'User password (min 8 characters, lowercase and uppercase letters, number, special characters).'
                  example: 'V&Bop}E\Zyn?'
                phone:
                  type: string
                  description: 'User phone number.'
                  example: minima
                permission_id:
                  type: integer
                  description: 'Permission group identifier.'
                  example: 11
                superuser:
                  type: boolean
                  description: 'If set true user have full access regardless of permissions.'
                  example: false
      security: []
    delete:
      summary: 'Delete user account'
      operationId: deleteUserAccount
      description: 'Delete user account.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'User does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User does not exist'
      tags:
        - 'User management'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'User identifier.'
        example: 12
        required: true
        schema:
          type: integer
  '/api/invite/{token}':
    get:
      summary: 'Validate invite token'
      operationId: validateInviteToken
      description: 'Check validate invite token.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{'email': 'john@doe.com'}"
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The given token is invalid'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The given token is invalid'
      tags:
        - 'User management'
      security: []
    put:
      summary: 'Confirm invitation'
      operationId: confirmInvitation
      description: 'Confirm invitation and create new user account.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The given token is invalid'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The given token is invalid'
      tags:
        - 'User management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'User first name.'
                  example: commodi
                lastname:
                  type: string
                  description: 'User last name.'
                  example: voluptatem
                password:
                  type: string
                  description: 'User password (min 8 characters, lowercase and uppercase letters, number, special characters).'
                  example: '!~cTB3|>r8B\fZ<,+'
                phone:
                  type: string
                  description: 'User phone number.'
                  example: perspiciatis
              required:
                - firstname
                - lastname
                - password
      security: []
    parameters:
      -
        in: path
        name: token
        description: 'Invite token from invitation message.'
        example: suscipit
        required: true
        schema:
          type: string
  /api/permissions:
    get:
      summary: 'Get permissions group list'
      operationId: getPermissionsGroupList
      description: 'Return permissions list.'
      parameters:
        -
          in: query
          name: size
          description: 'Number of rows. Default: 50'
          example: 5
          required: false
          schema:
            type: integer
            description: 'Number of rows. Default: 50'
            example: 5
        -
          in: query
          name: page
          description: 'Number of page (pagination). Default: 1'
          example: 6
          required: false
          schema:
            type: integer
            description: 'Number of page (pagination). Default: 1'
            example: 6
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  total_rows: 100
                  total_pages: '4'
                  current_page: 1
                  has_more: true
                  data:
                    -
                      id: 1
                      name: 'Example group name'
                      permissions:
                        module:
                          - list
                          - create
                      is_default: 0
                properties:
                  total_rows:
                    type: integer
                    example: 100
                  total_pages:
                    type: string
                    example: '4'
                  current_page:
                    type: integer
                    example: 1
                  has_more:
                    type: boolean
                    example: true
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'Example group name'
                        permissions:
                          module:
                            - list
                            - create
                        is_default: 0
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Example group name'
                        permissions:
                          type: object
                          properties:
                            module:
                              type: array
                              example:
                                - list
                                - create
                              items:
                                type: string
                        is_default:
                          type: integer
                          example: 0
      tags:
        - 'User permissions'
      security: []
  /api/permission:
    put:
      summary: 'Create new persmission group'
      operationId: createNewPersmissionGroup
      description: "Create new persmission group. Permissions should look like this:\nprojects:list,create,update,delete;users:list"
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: "'projects:' does not contain a list of items."
                  errors:
                    permissions:
                      - "'projects:' does not contain a list of items."
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "'projects:' does not contain a list of items."
                  errors:
                    type: object
                    properties:
                      permissions:
                        type: array
                        example:
                          - "'projects:' does not contain a list of items."
                        items:
                          type: string
      tags:
        - 'User permissions'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Group permission name.'
                  example: velit
                permissions:
                  type: string
                  description: Permission.
                  example: nisi
                is_default:
                  type: boolean
                  description: 'Set permission default.'
                  example: true
              required:
                - name
                - permissions
      security: []
  '/api/permission/{id}':
    get:
      summary: 'Get persmission group details'
      operationId: getPersmissionGroupDetails
      description: 'Get persmission group details.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 'Example group name'
                  permissions:
                    module:
                      - list
                      - create
                  is_default: 0
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'Example group name'
                  permissions:
                    type: object
                    properties:
                      module:
                        type: array
                        example:
                          - list
                          - create
                        items:
                          type: string
                  is_default:
                    type: integer
                    example: 0
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Permission does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Permission does not exist'
      tags:
        - 'User permissions'
      security: []
    put:
      summary: 'Update persmission group'
      operationId: updatePersmissionGroup
      description: 'Update persmission group.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses: {  }
      tags:
        - 'User permissions'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Group permission name.'
                  example: aspernatur
                permissions:
                  type: string
                  description: Permission.
                  example: distinctio
                is_default:
                  type: boolean
                  description: 'Set permission default.'
                  example: true
      security: []
    delete:
      summary: 'Delete persmission group'
      operationId: deletePersmissionGroup
      description: 'Delete persmission group.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Permission does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Permission does not exist'
      tags:
        - 'User permissions'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Permission group identifier.'
        example: 10
        required: true
        schema:
          type: integer
  '/api/permission/{id}/add':
    put:
      summary: 'Add permission to persmission group'
      operationId: addPermissionToPersmissionGroup
      description: 'Add permission to persmission group.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Permission does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Permission does not exist'
      tags:
        - 'User permissions'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                object:
                  type: string
                  description: 'Object name.'
                  example: fugit
                action:
                  type: string
                  description: 'Action name (if not set, allow all actions).'
                  example: nemo
              required:
                - object
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Permission group identifier.'
        example: 7
        required: true
        schema:
          type: integer
  '/api/permission/{id}/del':
    delete:
      summary: 'Delete permission from persmission group'
      operationId: deletePermissionFromPersmissionGroup
      description: 'Delete permission from persmission group.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Authorization:'
          description: ''
          example: 'Bearer {TOKEN}'
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Permission does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Permission does not exist'
      tags:
        - 'User permissions'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                object:
                  type: string
                  description: 'Object name.'
                  example: rerum
                action:
                  type: string
                  description: 'Action name (if not set, allow all actions).'
                  example: quo
              required:
                - object
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Permission group identifier.'
        example: 8
        required: true
        schema:
          type: integer
  /api/logout:
    get:
      summary: Logout
      operationId: logout
      description: Logout.
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User registation'
      security: []
  /api/register:
    post:
      summary: 'Register new account'
      operationId: registerNewAccount
      description: 'Create new user account. After registration, a confirmation link is sent to the provided e-mail address.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: boolean
                example: true
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The provided email is already registered.'
                  errors:
                    email:
                      - 'The provided email is already registered.'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The provided email is already registered.'
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - 'The provided email is already registered.'
                        items:
                          type: string
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email address.'
                  example: john@doe.com
              required:
                - email
      security: []
  '/api/register/confirm/{token}':
    get:
      summary: 'Validate register token'
      operationId: validateRegisterToken
      description: 'Check validate register token from confirmation message.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{'email': 'john@doe.com'}"
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The provided email is already registered.'
                  errors:
                    email:
                      - 'The provided email is already registered.'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The provided email is already registered.'
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - 'The provided email is already registered.'
                        items:
                          type: string
      tags:
        - 'User registation'
      security: []
    post:
      summary: 'Confirm register'
      operationId: confirmRegister
      description: 'Confirm register and finish registration.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'Invalid register token.'
                  errors:
                    token:
                      - 'Invalid register token.'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Invalid register token.'
                  errors:
                    type: object
                    properties:
                      token:
                        type: array
                        example:
                          - 'Invalid register token.'
                        items:
                          type: string
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: 'User first name.'
                  example: asperiores
                lastname:
                  type: string
                  description: 'User last name.'
                  example: totam
                password:
                  type: string
                  description: 'User password (min 8 characters, lowercase and uppercase letters, number, special characters).'
                  example: 'Z$=SfB+9_JOVFM<z]n='
                firm_identifier:
                  type: string
                  description: 'User firm name.'
                  example: sunt
                phone:
                  type: string
                  description: 'User phone number.'
                  example: qui
              required:
                - firstname
                - lastname
                - password
                - firm_identifier
                - phone
      security: []
    parameters:
      -
        in: path
        name: token
        description: 'Register token.'
        example: eos
        required: true
        schema:
          type: string
  /api/login:
    post:
      summary: 'Get token'
      operationId: getToken
      description: 'Return auth bearer Token.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'The provided credentials are incorrect.'
                  errors:
                    email:
                      - 'The provided credentials are incorrect.'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'The provided credentials are incorrect.'
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - 'The provided credentials are incorrect.'
                        items:
                          type: string
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Account e-mail address'
                  example: rowe.zita@example.net
                password:
                  type: string
                  description: 'Account password'
                  example: 'U#c]kN3;\L'
                device_name:
                  type: string
                  description: 'Device name'
                  example: qui
              required:
                - email
                - password
                - device_name
      security: []
  /api/forgot-password:
    post:
      summary: 'Forgot password'
      operationId: forgotPassword
      description: 'Send password reset link'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'User does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User does not exist'
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Account e-mail address'
                  example: nkuphal@example.org
                firm_id:
                  type: integer
                  description: 'Firm identifier (if e-mail address exist in more than once firms)'
                  example: 17
              required:
                - email
      security: []
  /api/reset-password:
    get:
      summary: 'Validate token reset password'
      operationId: validateTokenResetPassword
      description: 'Validate token reset password'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: 'forgot password token'
                  example: quaerat
                email:
                  type: string
                  description: 'Account e-mail address'
                  example: emely.schuppe@example.org
              required:
                - token
                - email
      security: []
    post:
      summary: 'Reset password'
      operationId: resetPassword
      description: 'Send password reset link'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: 'forgot password token'
                  example: molestiae
                email:
                  type: string
                  description: 'Account e-mail address'
                  example: irodriguez@example.org
                password:
                  type: string
                  description: 'User password (min 8 characters, lowercase and uppercase letters, number, special characters).'
                  example: 8QFdEgm
              required:
                - token
                - email
                - password
      security: []
  /api/get-email-firm-ids:
    get:
      summary: 'Get email firm ids'
      operationId: getEmailFirmIds
      description: "Get user email assigned firm identifiers\nBecause e-mail addresses may be repeated within other companies, if the e-mail address exists more than once,\nyou must enter the company ID when logging in / remembering the password."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: true
                  message: 'User does not exist'
                properties:
                  error:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User does not exist'
      tags:
        - 'User registation'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Account e-mail address'
                  example: sincere.klocko@example.com
              required:
                - email
      security: []
tags:
  -
    name: Projects
    description: ''
  -
    name: 'User management'
    description: ''
  -
    name: 'User permissions'
    description: ''
  -
    name: 'User registation'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
